trigger:
- '*'

pr:
- '*'

variables:
- name: kv-access-token
  value: ''
- group: AzureKeyVault
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
- name: DotNetCoreVersion
  value: 3.0.100-preview5-011568
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core
    inputs:
      version: $(DotNetCoreVersion)
  - powershell: ./build.ps1 -ci
    displayName: Invoke build.ps1
    condition: eq(variables['kv-access-token'], '')
  - powershell: ./build.ps1 -ci /p:AzureKeyVaultClientSecret=$(kv-access-token)
    displayName: Invoke build.ps1
    condition: ne(variables['kv-access-token'], '')
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Windows
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      pathtoPublish: 'artifacts/'
      artifactName: 'Packages'
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:

  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.105'
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core Latest
    inputs:
      version: $(DotNetCoreVersion)
# Once https://github.com/Microsoft/azure-pipelines-tasks/pull/9729 becomes generally available, use
# DotNetCoreInstaller@1 instead
  - script: cp -R /opt/hostedtoolcache/dncs/2.2.105/x64/shared/* /opt/hostedtoolcache/dncs/$(DotNetCoreVersion)/x64/shared && dotnet --info
    displayName: Workaround limitations in DotNetCoreInstaller V0
  - script: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Linux
      testRunner: vstest
      testResultsFiles: '**/*.trx'
